export const carrierList = [
  { id: 'UPS', name: 'UPS' },
  { id: 'USPS', name: 'USPS' },
  { id: 'FedEx', name: 'FedEx' },
  { id: 'Airborne', name: 'Airborne' },
  { id: 'OnTrac', name: 'OnTrac' },
  { id: 'DHL Ecommerce - US', name: 'DHL Ecommerce - US' },
  { id: 'DHL', name: 'DHL' },
  { id: 'LS', name: 'LS' },
  { id: 'UDS', name: 'UDS' },
  { id: 'UPSMI', name: 'UPSMI' },
  { id: 'FDX', name: 'FDX' },
  { id: 'PILOT', name: 'PILOT' },
  { id: 'ESTES', name: 'ESTES' },
  { id: 'SAIA', name: 'SAIA' },
  { id: 'FDS Express', name: 'FDS Express' },
  { id: 'Seko Worldwide', name: 'Seko Worldwide' },
  { id: 'HIT Delivery', name: 'HIT Delivery' },
  { id: 'FEDEXSP', name: 'FEDEXSP' },
  { id: 'RL Carriers', name: 'RL Carriers' },
  { id: 'Metropolitan Warehouse & Delivery', name: 'Metropolitan Warehouse & Delivery' },
  { id: 'China Post', name: 'China Post' },
  { id: 'YunExpress', name: 'YunExpress' },
  { id: 'Yellow Freight Sys', name: 'Yellow Freight Sys' },
  { id: 'AIT Worldwide Logistics', name: 'AIT Worldwide Logistics' },
  { id: 'Chukou1', name: 'Chukou1' },
  { id: 'Sendle', name: 'Sendle' },
  { id: 'Landmark Global', name: 'Landmark Global' },
  { id: 'Sunyou', name: 'Sunyou' },
  { id: 'Yanwen', name: 'Yanwen' },
  { id: '4PX', name: '4PX' },
  { id: 'GLS', name: 'GLS' },
  { id: 'OSM Worldwide', name: 'OSM Worldwide' },
  { id: 'FIRST MILE', name: 'FIRST MILE' },
  { id: 'AM Trucking', name: 'AM Trucking' },
  { id: 'CEVA', name: 'CEVA' },
  { id: 'India Post', name: 'India Post' },
  { id: 'SF Express', name: 'SF Express' },
  { id: 'CNE', name: 'CNE' },
  { id: 'TForce Freight', name: 'TForce Freight' },
  { id: 'AxleHire', name: 'AxleHire' },
  { id: 'LSO', name: 'LSO' },
  { id: 'Royal Mail', name: 'Royal Mail' },
  { id: 'ABF Freight System', name: 'ABF Freight System' },
  { id: 'WanB', name: 'WanB' },
  { id: 'Roadrunner Freight', name: 'Roadrunner Freight' },
  { id: 'Meyer Distribution', name: 'Meyer Distribution' },
  { id: 'AAA Cooper', name: 'AAA Cooper' },
  { id: 'Canada Post', name: 'Canada Post' },
  { id: 'Southeastern Freight Lines', name: 'Southeastern Freight Lines' },
  { id: 'Japan Post', name: 'Japan Post' },
  { id: 'Correos de Mexico', name: 'Correos de Mexico' },
  { id: 'XPO Logistics', name: 'XPO Logistics' },
  { id: 'JD Logistics', name: 'JD Logistics' },
  { id: 'YDH', name: 'YDH' },
  { id: 'JCEX', name: 'JCEX' },
  { id: 'Flyt', name: 'Flyt' },
  { id: 'Deutsche Post', name: 'Deutsche Post' },
  { id: 'Better Trucks', name: 'Better Trucks' },
  { id: 'Asendia', name: 'Asendia' },
  { id: 'SFC', name: 'SFC' },
  { id: 'UBI', name: 'UBI' },
  { id: 'ePost Global', name: 'ePost Global' },
  { id: 'YF Logistics', name: 'YF Logistics' },
  { id: 'RXO', name: 'RXO' },
  { id: 'Estes Express', name: 'Estes Express' },
  { id: 'Shypmax', name: 'Shypmax' },
  { id: 'WIN.IT America', name: 'WIN.IT America' },
  { id: 'PITT OHIO', name: 'PITT OHIO' },
  { id: 'PostNord Sweden', name: 'PostNord Sweden' },
  { id: 'Equick', name: 'Equick' },
  { id: 'Whistl', name: 'Whistl' },
  { id: 'Tusou', name: 'Tusou' },
  { id: 'Shiprocket', name: 'Shiprocket' },
  { id: 'DTDC', name: 'DTDC' },
  { id: 'PTS', name: 'PTS' }
];
